package com.abutton.game;

import android.view.KeyEvent;
import android.view.MotionEvent;

import com.abutton.game.utility.AdvancedMotion;

/**
 * Created by Dragonz on 22/06/2015.
 * class that receives and processes input events
 */
public abstract class GameInput {

    public GameInput() {}

    /**
     * Called by {@link Game} every time this input is set as the current input for the game.
     * If overriding this method {@code super.onSet()} needs to be called first.
     */
    public void onSet() {}

    /**
     * Package only visible method used to encapsulate {@code void onTouch(MotionEvent event)}.
     */
    void onTouchEvent(MotionEvent event) {
        // feeds the event to the Advanced Motion listener
        AdvancedMotion.feed(event);
        // interacts with all the elements inside this Input View
        Game.getLayer().interact(event);
        // user defined input management
        onTouch(event);
    }

    // called when there is a key event
    @SuppressWarnings("unused")
    public void onKeyDown(KeyEvent event) {}
    @SuppressWarnings("unused")
    public void onKeyUp(KeyEvent event) {}

    /**
     * Automatically called when back key is pressed on the phone.
     * {@code return true;} if you want to avoid executing the default action (closing)
     * return false otherwise.
     * @return true if you intercepted the action, false if you didn't
     */
    public abstract boolean onBackPressed();
    /**
     * Automatically called when a touch event is generated by the user.
     * @param event {@link MotionEvent} containing the information about the generated event.
     */
    public abstract void onTouch(MotionEvent event);

}
